import type { ParsedTemplate, ValidationEntry } from '@/types';

export const SAMPLE_SPECTORA_TEMPLATE: ParsedTemplate = {
  name: 'InterNACHI Standard Residential Template',
  sourceFile: 'internachi-residential-spectora.xlsx',
  sourcePlatform: 'spectora',
  sections: [
    {
      name: 'Roofing System',
      sortOrder: 1,
      items: [
        {
          name: 'Roof Covering & Shingles',
          sortOrder: 1,
          comments: [
            {
              name: 'Asphalt Shingles Inspected',
              text: 'The asphalt shingles were inspected from the ground with binoculars and rooftop walking where accessible. Shingles are architectural composite style.',
              commentType: 'info',
              category: -1,
              answerType: 'text',
              multipleChoiceOptions: null,
              recommendation: null,
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'Main Roof',
              defaultEstimateMin: null,
              defaultEstimateMax: null,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 142,
            },
            {
              name: 'Damaged or Missing Shingles',
              text: 'Damaged, lifted, or missing shingles observed on the south-facing slope. This can lead to moisture intrusion into the decking and attic.',
              commentType: 'defect',
              category: 1,
              answerType: 'text',
              multipleChoiceOptions: null,
              recommendation: 'Recommend evaluation and repair by a licensed roofing contractor to prevent leaks.',
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'South Slope',
              defaultEstimateMin: 400,
              defaultEstimateMax: 1200,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 89,
            },
            {
              name: 'Steep Roof Limitation',
              text: 'Certain upper slopes of the roof were not walked due to excessive pitch and safety precautions.',
              commentType: 'limit',
              category: 0,
              answerType: 'text',
              multipleChoiceOptions: null,
              recommendation: 'Inspected from eaves and ground level only.',
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'Upper Dormers',
              defaultEstimateMin: null,
              defaultEstimateMax: null,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 45,
            },
          ],
        },
        {
          name: 'Gutters & Downspouts',
          sortOrder: 2,
          comments: [
            {
              name: 'Gutters Clogged with Debris',
              text: 'Heavy accumulation of organic debris and leaves observed in the gutters. Obstructed gutters can cause overflow against fascia and foundation.',
              commentType: 'defect',
              category: 1,
              answerType: 'checkbox',
              multipleChoiceOptions: null,
              recommendation: 'Clean all gutters and downspout extensions thoroughly.',
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'Front and Rear Eaves',
              defaultEstimateMin: 150,
              defaultEstimateMax: 300,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 110,
            },
            {
              name: 'Downspout Terminating Near Foundation',
              text: 'Downspout discharge ends within 2 feet of foundation wall. Stormwater should discharge at least 5 to 6 feet away.',
              commentType: 'defect',
              category: 1,
              answerType: 'text',
              multipleChoiceOptions: null,
              recommendation: 'Install downspout extensions or splash blocks to redirect water away from basement/crawlspace.',
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'Northwest Corner',
              defaultEstimateMin: 50,
              defaultEstimateMax: 150,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 96,
            },
          ],
        },
      ],
    },
    {
      name: 'Electrical System',
      sortOrder: 2,
      items: [
        {
          name: 'Service Panel & Breakers',
          sortOrder: 1,
          comments: [
            {
              name: 'Main Service Panel 200A',
              text: 'Main service panel is located in the basement, rated at 200 amps, 120/240V, manufactured by Square D. Breakers are properly labeled.',
              commentType: 'info',
              category: -1,
              answerType: 'text',
              multipleChoiceOptions: null,
              recommendation: null,
              defaultValue: '200A',
              defaultValue2: null,
              defaultUnitType: 'Amps',
              defaultLocation: 'Basement Utility Room',
              defaultEstimateMin: null,
              defaultEstimateMax: null,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 215,
            },
            {
              name: 'Double-Tapped Neutral / Breaker',
              text: 'Double-tapped neutral conductor observed on the bus bar. Each neutral conductor must terminate in an individual terminal to prevent loose connections and overheating.',
              commentType: 'defect',
              category: 1,
              answerType: 'checkbox',
              multipleChoiceOptions: null,
              recommendation: 'Correction by a licensed electrician is advised.',
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'Main Distribution Panel',
              defaultEstimateMin: 200,
              defaultEstimateMax: 450,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 64,
            },
          ],
        },
        {
          name: 'GFCI & AFCI Protection',
          sortOrder: 2,
          comments: [
            {
              name: 'Missing GFCI in Kitchen / Wet Bar',
              text: 'Receptacles located within 6 feet of the sink in the kitchen are not protected by a Ground Fault Circuit Interrupter (GFCI).',
              commentType: 'defect',
              category: 1,
              answerType: 'checkbox',
              multipleChoiceOptions: null,
              recommendation: 'Upgrade receptacles to GFCI protection for shock prevention.',
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'Kitchen Countertops',
              defaultEstimateMin: 120,
              defaultEstimateMax: 250,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 180,
            },
          ],
        },
      ],
    },
    {
      name: 'Plumbing System',
      sortOrder: 3,
      items: [
        {
          name: 'Water Heater',
          sortOrder: 1,
          comments: [
            {
              name: 'Water Heater Details',
              text: '50-gallon natural gas water heater located in the mechanical room. Approximate age: 6 years.',
              commentType: 'info',
              category: -1,
              answerType: 'text',
              multipleChoiceOptions: null,
              recommendation: null,
              defaultValue: '50 Gallons',
              defaultValue2: null,
              defaultUnitType: 'gal',
              defaultLocation: 'Mechanical Room',
              defaultEstimateMin: null,
              defaultEstimateMax: null,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 175,
            },
            {
              name: 'TPR Discharge Pipe Missing / Short',
              text: 'The Temperature-Pressure Relief (TPR) valve discharge tube is missing or does not terminate within 6 inches of the floor.',
              commentType: 'defect',
              category: 1,
              answerType: 'checkbox',
              multipleChoiceOptions: null,
              recommendation: 'Install proper discharge pipe terminating safely near floor to prevent scalding hazards.',
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'Water Heater',
              defaultEstimateMin: 75,
              defaultEstimateMax: 175,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 120,
            },
          ],
        },
        {
          name: 'Drainage & Waste Piping',
          sortOrder: 2,
          comments: [
            {
              name: 'Active Leak Under Vanity',
              text: 'Moisture and active drip observed at the P-trap slip joint beneath the hall bathroom vanity sink.',
              commentType: 'defect',
              category: 1,
              answerType: 'text',
              multipleChoiceOptions: null,
              recommendation: 'Tighten or replace the slip washer / P-trap assembly to prevent water damage.',
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'Hall Bath Vanity',
              defaultEstimateMin: 100,
              defaultEstimateMax: 220,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 83,
            },
          ],
        },
      ],
    },
    {
      name: 'HVAC Heating & Cooling',
      sortOrder: 4,
      items: [
        {
          name: 'Central Air Conditioner',
          sortOrder: 1,
          comments: [
            {
              name: 'AC Exterior Condenser Unit',
              text: 'Carrier 3-ton exterior split system condensing unit. Operates with R-410A refrigerant.',
              commentType: 'info',
              category: -1,
              answerType: 'text',
              multipleChoiceOptions: null,
              recommendation: null,
              defaultValue: '3-Ton',
              defaultValue2: null,
              defaultUnitType: 'tons',
              defaultLocation: 'East Exterior Wall',
              defaultEstimateMin: null,
              defaultEstimateMax: null,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 130,
            },
            {
              name: 'AC Temperature Split Normal',
              text: 'Differential temperature between supply and return air measured at 18 degrees F, within standard operating range (15-20°F).',
              commentType: 'info',
              category: -1,
              answerType: 'number',
              multipleChoiceOptions: null,
              recommendation: null,
              defaultValue: '18',
              defaultValue2: null,
              defaultUnitType: '°F',
              defaultLocation: 'Air Handler',
              defaultEstimateMin: null,
              defaultEstimateMax: null,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 95,
            },
            {
              name: 'Damaged Fin Coils on Condenser',
              text: 'Condenser fins on the exterior unit are bent or crushed in several areas, restricting air flow through the coil.',
              commentType: 'defect',
              category: 1,
              answerType: 'text',
              multipleChoiceOptions: null,
              recommendation: 'Straighten with a fin comb tool during routine HVAC seasonal servicing.',
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'Outdoor Unit',
              defaultEstimateMin: 100,
              defaultEstimateMax: 200,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 48,
            },
          ],
        },
      ],
    },
  ],
};

export const SAMPLE_VALIDATION_LOGS: ValidationEntry[] = [
  {
    rowNumber: 1,
    status: 'success',
    message: 'Parsed section "Roofing System" with 2 items and 5 comments',
  },
  {
    rowNumber: 6,
    status: 'warning',
    message: 'Normalized comment type "deficiency" → "defect" for row 6',
    fieldName: 'Comment Type',
  },
  {
    rowNumber: 11,
    status: 'success',
    message: 'Parsed section "Electrical System" with 2 items and 3 comments',
  },
  {
    rowNumber: 15,
    status: 'warning',
    message: 'Empty "Recommendation" auto-defaulted to null',
    fieldName: 'Recommendation',
  },
  {
    rowNumber: 18,
    status: 'success',
    message: 'Parsed section "Plumbing System" with 2 items and 3 comments',
  },
  {
    rowNumber: 22,
    status: 'success',
    message: 'Parsed section "HVAC Heating & Cooling" with 1 item and 3 comments',
  },
];
