import type { ParsedTemplate, ValidationEntry } from '@/types';

export const SAMPLE_SPECTORA_TEMPLATE: ParsedTemplate = {
  name: 'InterNACHI Standard Residential Template',
  sourceFile: 'internachi-residential-spectora.xlsx',
  sourcePlatform: 'spectora',
  status: 'completed',
  lastUsedAt: 'Today, 2:15 PM',
  description: 'Comprehensive 4-point residential home inspection template compliant with InterNACHI standards.',
  sections: [
    {
      name: 'Roofing System',
      sortOrder: 1,
      items: [
        {
          name: 'Roof Covering & Shingles',
          sortOrder: 1,
          comments: [
            {
              name: 'Asphalt Shingles Inspected',
              text: 'The asphalt shingles were inspected from the ground with binoculars and rooftop walking where accessible. Shingles are architectural composite style.',
              commentType: 'info',
              category: -1,
              answerType: 'text',
              multipleChoiceOptions: null,
              recommendation: null,
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'Main Roof',
              defaultEstimateMin: null,
              defaultEstimateMax: null,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 142,
            },
            {
              name: 'Damaged or Missing Shingles',
              text: 'Damaged, lifted, or missing shingles observed on the south-facing slope. This can lead to moisture intrusion into the decking and attic.',
              commentType: 'defect',
              category: 1,
              answerType: 'text',
              multipleChoiceOptions: null,
              recommendation: 'Recommend evaluation and repair by a licensed roofing contractor to prevent leaks.',
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'South Slope',
              defaultEstimateMin: 400,
              defaultEstimateMax: 1200,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 89,
            },
            {
              name: 'Steep Roof Limitation',
              text: 'Certain upper slopes of the roof were not walked due to excessive pitch and safety precautions.',
              commentType: 'limit',
              category: 0,
              answerType: 'text',
              multipleChoiceOptions: null,
              recommendation: 'Inspected from eaves and ground level only.',
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'Upper Dormers',
              defaultEstimateMin: null,
              defaultEstimateMax: null,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 45,
            },
          ],
        },
        {
          name: 'Gutters & Downspouts',
          sortOrder: 2,
          comments: [
            {
              name: 'Gutters Clogged with Debris',
              text: 'Heavy accumulation of organic debris and leaves observed in the gutters. Obstructed gutters can cause overflow against fascia and foundation.',
              commentType: 'defect',
              category: 1,
              answerType: 'checkbox',
              multipleChoiceOptions: null,
              recommendation: 'Clean all gutters and downspout extensions thoroughly.',
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'Front and Rear Eaves',
              defaultEstimateMin: 150,
              defaultEstimateMax: 300,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 110,
            },
            {
              name: 'Downspout Terminating Near Foundation',
              text: 'Downspout discharge ends within 2 feet of foundation wall. Stormwater should discharge at least 5 to 6 feet away.',
              commentType: 'defect',
              category: 1,
              answerType: 'text',
              multipleChoiceOptions: null,
              recommendation: 'Install downspout extensions or splash blocks to redirect water away from basement/crawlspace.',
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'Northwest Corner',
              defaultEstimateMin: 50,
              defaultEstimateMax: 150,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 96,
            },
          ],
        },
      ],
    },
    {
      name: 'Electrical System',
      sortOrder: 2,
      items: [
        {
          name: 'Service Panel & Breakers',
          sortOrder: 1,
          comments: [
            {
              name: 'Main Service Panel 200A',
              text: 'Main service panel is located in the basement, rated at 200 amps, 120/240V, manufactured by Square D. Breakers are properly labeled.',
              commentType: 'info',
              category: -1,
              answerType: 'text',
              multipleChoiceOptions: null,
              recommendation: null,
              defaultValue: '200A',
              defaultValue2: null,
              defaultUnitType: 'Amps',
              defaultLocation: 'Basement Utility Room',
              defaultEstimateMin: null,
              defaultEstimateMax: null,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 215,
            },
            {
              name: 'Double-Tapped Neutral / Breaker',
              text: 'Double-tapped neutral conductor observed on the bus bar. Each neutral conductor must terminate in an individual terminal to prevent loose connections and overheating.',
              commentType: 'defect',
              category: 1,
              answerType: 'checkbox',
              multipleChoiceOptions: null,
              recommendation: 'Correction by a licensed electrician is advised.',
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'Main Distribution Panel',
              defaultEstimateMin: 200,
              defaultEstimateMax: 450,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 64,
            },
          ],
        },
        {
          name: 'GFCI & AFCI Protection',
          sortOrder: 2,
          comments: [
            {
              name: 'Missing GFCI in Kitchen / Wet Bar',
              text: 'Receptacles located within 6 feet of the sink in the kitchen are not protected by a Ground Fault Circuit Interrupter (GFCI).',
              commentType: 'defect',
              category: 1,
              answerType: 'checkbox',
              multipleChoiceOptions: null,
              recommendation: 'Upgrade receptacles to GFCI protection for shock prevention.',
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'Kitchen Countertops',
              defaultEstimateMin: 120,
              defaultEstimateMax: 250,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 180,
            },
          ],
        },
      ],
    },
    {
      name: 'Plumbing System',
      sortOrder: 3,
      items: [
        {
          name: 'Water Heater',
          sortOrder: 1,
          comments: [
            {
              name: 'Water Heater Details',
              text: '50-gallon natural gas water heater located in the mechanical room. Approximate age: 6 years.',
              commentType: 'info',
              category: -1,
              answerType: 'text',
              multipleChoiceOptions: null,
              recommendation: null,
              defaultValue: '50 Gallons',
              defaultValue2: null,
              defaultUnitType: 'gal',
              defaultLocation: 'Mechanical Room',
              defaultEstimateMin: null,
              defaultEstimateMax: null,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 175,
            },
            {
              name: 'TPR Discharge Pipe Missing / Short',
              text: 'The Temperature-Pressure Relief (TPR) valve discharge tube is missing or does not terminate within 6 inches of the floor.',
              commentType: 'defect',
              category: 1,
              answerType: 'checkbox',
              multipleChoiceOptions: null,
              recommendation: 'Install proper discharge pipe terminating safely near floor to prevent scalding hazards.',
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'Water Heater',
              defaultEstimateMin: 75,
              defaultEstimateMax: 175,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 120,
            },
          ],
        },
        {
          name: 'Drainage & Waste Piping',
          sortOrder: 2,
          comments: [
            {
              name: 'Active Leak Under Vanity',
              text: 'Moisture and active drip observed at the P-trap slip joint beneath the hall bathroom vanity sink.',
              commentType: 'defect',
              category: 1,
              answerType: 'text',
              multipleChoiceOptions: null,
              recommendation: 'Tighten or replace the slip washer / P-trap assembly to prevent water damage.',
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'Hall Bath Vanity',
              defaultEstimateMin: 100,
              defaultEstimateMax: 220,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 83,
            },
          ],
        },
      ],
    },
    {
      name: 'HVAC Heating & Cooling',
      sortOrder: 4,
      items: [
        {
          name: 'Central Air Conditioner',
          sortOrder: 1,
          comments: [
            {
              name: 'AC Exterior Condenser Unit',
              text: 'Carrier 3-ton exterior split system condensing unit. Operates with R-410A refrigerant.',
              commentType: 'info',
              category: -1,
              answerType: 'text',
              multipleChoiceOptions: null,
              recommendation: null,
              defaultValue: '3-Ton',
              defaultValue2: null,
              defaultUnitType: 'tons',
              defaultLocation: 'East Exterior Wall',
              defaultEstimateMin: null,
              defaultEstimateMax: null,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 130,
            },
            {
              name: 'AC Temperature Split Normal',
              text: 'Differential temperature between supply and return air measured at 18 degrees F, within standard operating range (15-20°F).',
              commentType: 'info',
              category: -1,
              answerType: 'number',
              multipleChoiceOptions: null,
              recommendation: null,
              defaultValue: '18',
              defaultValue2: null,
              defaultUnitType: '°F',
              defaultLocation: 'Air Handler',
              defaultEstimateMin: null,
              defaultEstimateMax: null,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 95,
            },
            {
              name: 'Damaged Fin Coils on Condenser',
              text: 'Condenser fins on the exterior unit are bent or crushed in several areas, restricting air flow through the coil.',
              commentType: 'defect',
              category: 1,
              answerType: 'text',
              multipleChoiceOptions: null,
              recommendation: 'Straighten with a fin comb tool during routine HVAC seasonal servicing.',
              defaultValue: null,
              defaultValue2: null,
              defaultUnitType: null,
              defaultLocation: 'Outdoor Unit',
              defaultEstimateMin: 100,
              defaultEstimateMax: 200,
              locked: false,
              simpleFormat: false,
              disablePhotos: false,
              uses: 48,
            },
          ],
        },
      ],
    },
  ],
};

export const DEMO_INITIAL_TEMPLATES: ParsedTemplate[] = [
  SAMPLE_SPECTORA_TEMPLATE,
  {
    name: 'Pre-Purchase Historic Home Inspection',
    sourceFile: 'historic-home-standards.xlsx',
    sourcePlatform: 'spectora',
    status: 'pending',
    lastUsedAt: 'Yesterday, 4:45 PM',
    description: 'Specialized evaluation template for vintage masonry, knob-and-tube wiring, and historic architectural elements.',
    sections: [
      {
        name: 'Structural & Masonry Foundation',
        sortOrder: 1,
        items: [
          {
            name: 'Stone & Mortar Foundations',
            sortOrder: 1,
            comments: [
              {
                name: 'Mortar Deterioration / Repointing Needed',
                text: 'Efflorescence and crumbling lime mortar observed along the interior foundation walls. Tuckpointing recommended.',
                commentType: 'defect',
                category: 1,
                answerType: 'text',
                multipleChoiceOptions: null,
                recommendation: 'Contact a historic masonry restoration specialist.',
                defaultValue: null,
                defaultValue2: null,
                defaultUnitType: null,
                defaultLocation: 'Basement Perimeter',
                defaultEstimateMin: 1200,
                defaultEstimateMax: 3500,
                locked: false,
                simpleFormat: false,
                disablePhotos: false,
                uses: 64,
              },
            ],
          },
        ],
      },
      {
        name: 'Vintage Electrical & Wiring',
        sortOrder: 2,
        items: [
          {
            name: 'Knob & Tube Identification',
            sortOrder: 1,
            comments: [
              {
                name: 'Active Knob-and-Tube Wiring',
                text: 'Visible ungrounded knob-and-tube wiring remains active in attic floor joists.',
                commentType: 'defect',
                category: 1,
                answerType: 'text',
                multipleChoiceOptions: null,
                recommendation: 'Recommend replacement by a licensed master electrician for insurance compliance.',
                defaultValue: null,
                defaultValue2: null,
                defaultUnitType: null,
                defaultLocation: 'Attic Space',
                defaultEstimateMin: 2500,
                defaultEstimateMax: 6000,
                locked: false,
                simpleFormat: false,
                disablePhotos: false,
                uses: 52,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: 'New Construction 1-Year Warranty Inspection',
    sourceFile: 'new-construction-checklist.xlsx',
    sourcePlatform: 'spectora',
    status: 'new_formed',
    lastUsedAt: '3 days ago',
    description: 'Builder punch-list template covering thermal bridging, drywall settlement cracks, and exterior grading.',
    sections: [
      {
        name: 'Interior Finishes & Drywall',
        sortOrder: 1,
        items: [
          {
            name: 'Drywall Nail Pops & Corner Cracks',
            sortOrder: 1,
            comments: [
              {
                name: 'Standard Settlement Cracks Observed',
                text: 'Minor cosmetic hairline cracks noted at ceiling corner joints due to standard truss uplift and lumber drying.',
                commentType: 'info',
                category: -1,
                answerType: 'text',
                multipleChoiceOptions: null,
                recommendation: 'Submit on 11-month builder punch list for cosmetic patching and painting.',
                defaultValue: null,
                defaultValue2: null,
                defaultUnitType: null,
                defaultLocation: 'Upstairs Hallway',
                defaultEstimateMin: null,
                defaultEstimateMax: null,
                locked: false,
                simpleFormat: false,
                disablePhotos: false,
                uses: 33,
              },
            ],
          },
        ],
      },
    ],
  },
];

export const SAMPLE_VALIDATION_LOGS: ValidationEntry[] = [
  {
    rowNumber: 1,
    status: 'success',
    message: 'Parsed section "Roofing System" with 2 items and 5 comments',
  },
  {
    rowNumber: 6,
    status: 'warning',
    message: 'Normalized comment type "deficiency" → "defect" for row 6',
    fieldName: 'Comment Type',
  },
  {
    rowNumber: 11,
    status: 'success',
    message: 'Parsed section "Electrical System" with 2 items and 3 comments',
  },
  {
    rowNumber: 15,
    status: 'warning',
    message: 'Empty "Recommendation" auto-defaulted to null',
    fieldName: 'Recommendation',
  },
  {
    rowNumber: 18,
    status: 'success',
    message: 'Parsed section "Plumbing System" with 2 items and 3 comments',
  },
  {
    rowNumber: 22,
    status: 'success',
    message: 'Parsed section "HVAC Heating & Cooling" with 1 item and 3 comments',
  },
];

import type { InspectionProperty, AgentContact, MetricsSummary } from '@/types';

export const DEMO_AGENTS: AgentContact[] = [
  {
    id: 'agent-1',
    name: 'Rushil Chhaya',
    email: 'rushil@inspectionco.com',
    phone: '(303) 555-0192',
    agency: 'My Inspection Company',
    team: 'Denver Metro Core',
    inspectionsCount: 42,
    buyerAgentCount: 26,
    sellerAgentCount: 16,
    activeInspections: 2,
    completedInspections: 40,
    rating: 4.98,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'agent-2',
    name: 'Sarah Jenkins',
    email: 'sarah.j@milehighinspect.com',
    phone: '(303) 555-0144',
    agency: 'Mile High Inspections',
    team: 'Boulder Foothills',
    inspectionsCount: 36,
    buyerAgentCount: 22,
    sellerAgentCount: 14,
    activeInspections: 1,
    completedInspections: 35,
    rating: 4.95,
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'agent-3',
    name: 'Maggie Johnson',
    email: 'maggie@compassrealty.com',
    phone: '(720) 555-0188',
    agency: 'Compass Colorado',
    team: 'South Denver Luxury',
    inspectionsCount: 28,
    buyerAgentCount: 19,
    sellerAgentCount: 9,
    activeInspections: 1,
    completedInspections: 27,
    rating: 4.92,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'agent-4',
    name: 'Jose Ferrara',
    email: 'jose@peakinspections.com',
    phone: '(719) 555-0112',
    agency: 'Peak Inspections CO',
    team: 'Springs Southern Tier',
    inspectionsCount: 25,
    buyerAgentCount: 15,
    sellerAgentCount: 10,
    activeInspections: 0,
    completedInspections: 25,
    rating: 4.88,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'agent-5',
    name: 'Daniel Ling',
    email: 'daniel@frontrangeinspections.com',
    phone: '(970) 555-0165',
    agency: 'Front Range Diagnostics',
    team: 'Northern Corridor',
    inspectionsCount: 21,
    buyerAgentCount: 12,
    sellerAgentCount: 9,
    activeInspections: 1,
    completedInspections: 20,
    rating: 4.91,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'agent-6',
    name: 'Tony Smith',
    email: 'tony.smith@coinspect.com',
    phone: '(303) 555-0173',
    agency: 'Colorado Inspection Group',
    team: 'West Metro',
    inspectionsCount: 18,
    buyerAgentCount: 11,
    sellerAgentCount: 7,
    activeInspections: 0,
    completedInspections: 18,
    rating: 4.86,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
];

export const DEMO_INSPECTIONS: InspectionProperty[] = [
  {
    id: 'insp-1',
    address: '1005 S Gaylord St',
    city: 'Denver',
    state: 'CO',
    zip: '80209',
    lat: 39.6978,
    lng: -104.9608,
    assignedAgent: {
      id: 'agent-1',
      name: 'Rushil Chhaya',
      email: 'rushil@inspectionco.com',
      phone: '(303) 555-0192',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      agency: 'My Inspection Company',
    },
    status: 'in_progress',
    scheduledTime: '5:20 am',
    scheduledDate: 'Today',
    inspectionType: 'InterNACHI Full Residential Inspection',
    clientName: 'Mark & Stephanie Davies',
    realtorAgent: 'Maggie Johnson (Compass)',
    price: 525,
    thumbnail: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=400&auto=format&fit=crop&q=80',
    notes: 'Access lockbox code 4921 at side porch. Focus on older foundation crawlspace and attic insulation.',
  },
  {
    id: 'insp-2',
    address: '2418 E 7th Ave',
    city: 'Denver',
    state: 'CO',
    zip: '80206',
    lat: 39.7282,
    lng: -104.9575,
    assignedAgent: {
      id: 'agent-1',
      name: 'Rushil Chhaya',
      email: 'rushil@inspectionco.com',
      phone: '(303) 555-0192',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      agency: 'My Inspection Company',
    },
    status: 'scheduled',
    scheduledTime: '9:30 am',
    scheduledDate: 'Today',
    inspectionType: 'Pre-Purchase Historic Home Inspection',
    clientName: 'Claire & Arthur Vance',
    realtorAgent: 'Tony Smith (CO Group)',
    price: 595,
    thumbnail: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=400&auto=format&fit=crop&q=80',
    notes: 'Tudor brick construction built 1928. Verify ungrounded 2-prong outlets and galvanized plumbing.',
  },
  {
    id: 'insp-3',
    address: '1420 Pearl St',
    city: 'Boulder',
    state: 'CO',
    zip: '80302',
    lat: 40.0182,
    lng: -105.2785,
    assignedAgent: {
      id: 'agent-2',
      name: 'Sarah Jenkins',
      email: 'sarah.j@milehighinspect.com',
      phone: '(303) 555-0144',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
      agency: 'Mile High Inspections',
    },
    status: 'completed',
    scheduledTime: '1:15 pm',
    scheduledDate: 'Yesterday',
    inspectionType: 'Residential Inspection + Continuous Radon Monitor',
    clientName: 'David Montgomery',
    realtorAgent: 'Sarah Jenkins',
    price: 650,
    thumbnail: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&auto=format&fit=crop&q=80',
    notes: 'Report published and delivered to buyer and listing agent. 3 minor defects reported.',
    completedAt: 'Yesterday, 4:45 pm',
  },
  {
    id: 'insp-4',
    address: '415 N Tejon St',
    city: 'Colorado Springs',
    state: 'CO',
    zip: '80903',
    lat: 38.8398,
    lng: -104.8235,
    assignedAgent: {
      id: 'agent-4',
      name: 'Jose Ferrara',
      email: 'jose@peakinspections.com',
      phone: '(719) 555-0112',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      agency: 'Peak Inspections CO',
    },
    status: 'scheduled',
    scheduledTime: '11:00 am',
    scheduledDate: 'Tomorrow',
    inspectionType: 'Single Family Residential Inspection',
    clientName: 'Elena Rostova',
    realtorAgent: 'Maggie Johnson (Compass)',
    price: 485,
    thumbnail: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&auto=format&fit=crop&q=80',
    notes: 'Client attending at 1:00 pm for walkthrough of findings with agent.',
  },
  {
    id: 'insp-5',
    address: '850 14th St',
    city: 'Lakewood',
    state: 'CO',
    zip: '80214',
    lat: 39.7392,
    lng: -105.0780,
    assignedAgent: {
      id: 'agent-1',
      name: 'Rushil Chhaya',
      email: 'rushil@inspectionco.com',
      phone: '(303) 555-0192',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      agency: 'My Inspection Company',
    },
    status: 'completed',
    scheduledTime: '8:00 am',
    scheduledDate: 'Sep 14',
    inspectionType: 'Pre-Listing Seller Inspection',
    clientName: 'Robert & Linda Chen',
    realtorAgent: 'Maggie Johnson (Compass)',
    price: 495,
    thumbnail: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&auto=format&fit=crop&q=80',
    notes: 'Comprehensive pre-listing report uploaded to MLS repository. Roof passed with 0 defects.',
    completedAt: 'Sep 14, 11:30 am',
  },
  {
    id: 'insp-6',
    address: '602 S College Ave',
    city: 'Fort Collins',
    state: 'CO',
    zip: '80524',
    lat: 40.5815,
    lng: -105.0772,
    assignedAgent: {
      id: 'agent-5',
      name: 'Daniel Ling',
      email: 'daniel@frontrangeinspections.com',
      phone: '(970) 555-0165',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      agency: 'Front Range Diagnostics',
    },
    status: 'in_progress',
    scheduledTime: '1:45 pm',
    scheduledDate: 'Today',
    inspectionType: 'New Construction 1-Year Builder Warranty Inspection',
    clientName: 'Marcus & Zoe Bell',
    realtorAgent: 'David Montgomery',
    price: 540,
    thumbnail: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=400&auto=format&fit=crop&q=80',
    notes: 'Thermal imaging sweep for missing insulation in cathedral ceiling and garage firewall.',
  },
];

export const DEMO_METRICS: MetricsSummary = {
  inspectionsTrend: [
    { month: 'Jan', currentYear: 18, previousYear: 14 },
    { month: 'Feb', currentYear: 24, previousYear: 19 },
    { month: 'Mar', currentYear: 31, previousYear: 25 },
    { month: 'Apr', currentYear: 38, previousYear: 29 },
    { month: 'May', currentYear: 46, previousYear: 36 },
    { month: 'Jun', currentYear: 52, previousYear: 42 },
    { month: 'Jul', currentYear: 48, previousYear: 40 },
    { month: 'Aug', currentYear: 55, previousYear: 44 },
    { month: 'Sep', currentYear: 51, previousYear: 41 },
    { month: 'Oct', currentYear: 44, previousYear: 35 },
    { month: 'Nov', currentYear: 32, previousYear: 26 },
    { month: 'Dec', currentYear: 28, previousYear: 22 },
  ],
  referralSources: [
    { name: 'Buyer & Listing Realtors', percentage: 46, count: 184, color: '#2563eb' },
    { name: 'Past Client Repeat & Referrals', percentage: 24, count: 96, color: '#10b981' },
    { name: 'Online Scheduler & Organic Search', percentage: 18, count: 72, color: '#f59e0b' },
    { name: 'Zillow, Redfin & MLS Portals', percentage: 12, count: 48, color: '#8b5cf6' },
  ],
  topAgents: [
    { name: 'Rushil Chhaya', inspections: 34, agency: 'My Inspection Company' },
    { name: 'Maggie Johnson', inspections: 28, agency: 'Compass Colorado' },
    { name: 'Jose Ferrara', inspections: 25, agency: 'Peak Inspections CO' },
    { name: 'Daniel Ling', inspections: 21, agency: 'Front Range Diagnostics' },
    { name: 'Tony Smith', inspections: 18, agency: 'Colorado Inspection Group' },
  ],
  revenueMonthly: [
    { month: 'Jan', currentYear: 9200, previousYear: 7100 },
    { month: 'Feb', currentYear: 12400, previousYear: 9600 },
    { month: 'Mar', currentYear: 16200, previousYear: 12800 },
    { month: 'Apr', currentYear: 19800, previousYear: 14900 },
    { month: 'May', currentYear: 23900, previousYear: 18500 },
    { month: 'Jun', currentYear: 27100, previousYear: 21400 },
    { month: 'Jul', currentYear: 25200, previousYear: 20200 },
    { month: 'Aug', currentYear: 28900, previousYear: 22600 },
    { month: 'Sep', currentYear: 26800, previousYear: 21000 },
    { month: 'Oct', currentYear: 22800, previousYear: 17800 },
    { month: 'Nov', currentYear: 16500, previousYear: 13200 },
    { month: 'Dec', currentYear: 14500, previousYear: 11100 },
  ],
  onlineSchedulerRevenue: 200850,
  partnershipRevenue: 12790,
  totalInspections: 142,
  avgInspectionFee: 475,
  avgTurnaroundHours: 3.4,
  satisfactionRate: 99.4,
};
